link:
  defaultPalette: 0
  display: "Link"
  contributor: "Nintendo"

# Not a real sprite
random:
  display: "Random"
  defaultPalette: 7 # 6 = random, 7 = default for chosen sprite
  contributor: "???"

# NOTE: File select harp-playing animation is probably broken for marin due to
# animation hacks. Doesn't really matter since linked games aren't supported,
# for now.
marin:
  defaultPalette: 3
  display: "Marin"
  contributor: "Stewmat"

  # Hacks for animation data, because I was too lazy to draw harp & flute
  # sprites (uses her 'singing' sprites instead).
  # Must be cautious to ensure that the length of the animation doesn't
  # change when hacking it, lest one sprite becomes faster than another!
  animationHacks:
    # Flute animation
    - agesLabel:    'animationData19f90'
      seasonsLabel: 'animationData19cf7'
      data: [
        60,0x34,0x00,
        30,0x35,0x01,
        60,0x36,0x01,
        30,0x35,0x00,
        60,0x34,0x00,
        15,0x35,0x01,
        0x7f,0x2e,0xff
      ]
    # Harp animation
    - agesLabel:    'animationData19faa'
      seasonsLabel: 'animationDataHarp'
      data: [
        40,0x34,0x00,
        12,0x35,0x01,
        40,0x36,0x01,
        12,0x35,0x00,
        40,0x34,0x00,
        12,0x35,0x01,
        40,0x36,0x01,
        12,0x35,0x00,
        40,0x34,0x00,
        12,0x35,0x01,
        0x01,0x36,0x81,
        0x7f,0x1c,0xff
      ]

demonlink:
  defaultPalette: 5
  display: "Demonic Link"
  contributor: "Stewmat"

likelike:
  defaultPalette: 3
  display: "Like-Like"
  contributor: "Stewmat"

nayru:
  defaultPalette: 1
  display: "Nayru"
  contributor: "Natsuru, Stewmat"

  # Nayru's harp animation is normal, but her flute animation is done by singing
  # instead. Some animation hacks are needed.
  # NOTE: Normally the flute animation data provides bit 6 (0x40) in its
  # animParameter (3rd byte of an animation frame), which tells the game to cut
  # the animation short for the unassigned strange flute, at 95 frames into the
  # animation. In the process of re-jigging the animation we no longer have a
  # line corresponding to frame 95. Doesn't really matter though, since the
  # strange flute is always assigned to a companion in the randomizer. However,
  # in the case that it wasn't, the animation would go on for far too long.
  animationHacks:
    - agesLabel:    'animationData19f90'
      seasonsLabel: 'animationData19cf7'
      data: [
        60, 0x2d, 0x00,
        30, 0x2c, 0x01,
        60, 0x2f, 0x01,
        30, 0x2c, 0x00,
        60, 0x2d, 0x00,
        15, 0x2c, 0x00,
        0x7f, 0x2c, 0xff
      ]

  # Also for the flute animation - prevents her from moving left and right
  gfxPointerHacks:
    specialObject00GfxPointers:
      45: [0x80, 'spr_link', 0x11c0, 0x04]
      47: [0x81, 'spr_link', 0x11c0, 0x04]

darklink:
  defaultPalette: 5
  display: "Dark Link"
  contributor: "revan_xviv"

goron:
  defaultPalette: 3
  display: "Goron"
  contributor: "Snow"

matty:
  defaultPalette: 3
  display: "Matty"
  contributor: "Madam Materia"

piratian:
  defaultPalette: 1
  display: "Piratian"
  contributor: "Snow"

rosa_key:
  defaultPalette: 3
  display: "Rosa (with key)"
  contributor: "Snow"

rosa_nokey:
  defaultPalette: 3
  display: "Rosa (no key)"
  contributor: "Snow"

subrosian:
  defaultPalette: 0
  display: "Subrosian"
  contributor: "Snow"

tokay:
  defaultPalette: 0
  display: "Tokay"
  contributor: "Snow"

zoroark:
  defaultPalette: 2
  display: "Zoroark"
  contributor: "Snow"

zora:
  defaultPalette: 1
  display: "Zora"
  contributor: "Mechsrule1"
